# Generated by Django 6.0.2 on 2026-02-21 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onchain_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('employer_address', models.CharField(max_length=66)),
                ('price_weight', models.IntegerField(default=50)),
                ('timeline_weight', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('BIDDING', 'Bidding'), ('REVEAL', 'Reveal'), ('SHORTLISTED', 'Shortlisted'), ('FINALIZED', 'Finalized')], default='BIDDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_address', models.CharField(max_length=66)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('timeline', models.IntegerField(blank=True, null=True)),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='marketplace.job')),
            ],
        ),
    ]
