# Generated by Django 6.0.2 on 2026-02-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder_address',
            field=models.CharField(db_index=True, max_length=66),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=78, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='revealed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer_address',
            field=models.CharField(db_index=True, max_length=66),
        ),
    ]
